# The URL the site will be built for
base_url = "https://aliasjeff.github.io"
title = "AliasJeff"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "apollo"
taxonomies = [{ name = "tags" }]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[search]
include_title = true
include_description = true
include_path = true
include_content = true
index_format = "elasticlunr_json"

[extra]
theme = "toggle"
socials = [
  { name = "github", url = "https://github.com/AliasJeff/", icon = "github" }
]
menu = [
  { name = "Home", url = "/", weight = 1 },
  { name = "About", url = "/about", weight = 2 },
  { name = "Projects", url = "/projects", weight = 3 },
  { name = "Posts", url = "/posts", weight = 4 },
  { name = "Tags", url = "/tags", weight = 5 },
]

toc = true
fancy_code = true
dynamic_note = true

favicon = "code.svg"

# Giscus Comments Configuration
[extra.giscus]
repo = "AliasJeff/alias-studio.github.io"
repo_id = "R_kgDOQs_HFw"
category = "General"
category_id = "DIC_kwDOQs_HF84C0Hvj"
mapping = "pathname"
strict = "0"
reactions_enabled = "1"
emit_metadata = "0"
input_position = "bottom"
theme = "preferred_color_scheme"
lang = "zh-CN"
loading = "lazy"

# See this for more options: https://github.com/not-matthias/apollo/blob/main/config.toml#L14
